---

services:
  caddy:
    image: caddy:2.9.1-alpine@sha256:b4e3952384eb9524a887633ce65c752dd7c71314d2c2acf98cd5c715aaa534f0  # yamllint disable-line rule:line-length
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "/etc/configs/Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "caddy_config:/config"

  alloy:
    image: grafana/alloy:v1.7.1@sha256:da938bc7dc6a96be31d3c93badc445aed115ca39357734de7a338f78fa342cf7  # yamllint disable-line rule:line-length
    entrypoint: /entrypoint-foo.sh
    command:
      - /bin/alloy
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    restart: unless-stopped
    environment:
      GCLOUD_HOSTED_METRICS_URL: "https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push"  # yamllint disable-line rule:line-length
      GCLOUD_HOSTED_LOGS_URL: "https://logs-prod-012.grafana.net/loki/api/v1/push"  # yamllint disable-line rule:line-length
      GCLOUD_SCRAPE_INTERVAL: 60s
    ports:
      - "12345:12345"
    volumes:
      - "/etc/configs/config.alloy:/etc/alloy/config.alloy"
      - "/etc/configs/entrypoint.sh:/entrypoint-foo.sh"
      - "/etc/secrets/gcloud_hosted_metrics_id:/run/secrets/gcloud_hosted_metrics_id:ro"
      - "/etc/secrets/gcloud_hosted_logs_id:/run/secrets/gcloud_hosted_logs_id:ro"
      - "/etc/secrets/gcloud_rw_api_key:/run/secrets/gcloud_rw_api_key:ro"
      - "alloy:/var/lib/alloy/data"
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  caddy_data:
  caddy_config:
  alloy:
